#pragma once
// The Phase-1 fuzzing loop.
//
//   pick seed -> mutate -> run instrumented target -> read coverage
//     -> new edges? keep the input   -> crash? save it   -> repeat
//
// The target is an in-process libFuzzer-style entry point:
//     int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size);
// which is exactly what the harnesses in harnesses/ expose, so the same target
// works here and under libFuzzer/AFL++ in the benchmark.
#include <cstdint>
#include <string>
#include <vector>

#include "nyx/corpus.hpp"

namespace nyx {

using TargetFn = int (*)(const uint8_t*, size_t);

struct EngineOptions {
  uint64_t seed = 0x9E3779B97F4A7C15ull;
  uint64_t max_iterations = 0;   // 0 => unbounded (use max_seconds)
  double max_seconds = 0.0;      // 0 => unbounded (use max_iterations)
  bool stop_on_first_crash = false;
  std::string crash_dir;         // if set, crashing inputs are written here
  bool quiet = false;
  // When false, inputs that discover new edges are NOT kept -- i.e. blind
  // fuzzing with no coverage feedback. Used as the ablation baseline that shows
  // how much the coverage guidance is actually worth.
  bool coverage_guided = true;
  // When true, candidates are generated by mutating the parsed DER tree
  // (structure-aware) instead of raw bytes. The Phase-2 differentiator; also
  // the ablation axis for "how much is structure awareness worth?".
  bool structure_aware = false;
  // When true (and structure_aware), inputs that look like X.509 certificates
  // also receive semantic, typed mutations (boundary dates, hostile serials,
  // malformed OIDs, duplicated extensions). Phase 2b.
  bool x509_semantic = false;
  // Scheduler for seed energy + operator selection (structure-aware mode).
  // Phase 3. kUniform is the control; kEntropy is rarity-weighted energy plus a
  // UCB1 operator bandit.
  enum class SchedulerKind { kUniform, kEntropy };
  SchedulerKind scheduler = SchedulerKind::kUniform;
};

struct FuzzStats {
  uint64_t iterations = 0;
  size_t corpus_size = 0;
  size_t total_edges = 0;        // cumulative distinct edges covered
  size_t crashes = 0;
  std::vector<uint8_t> first_crash;
  double elapsed_seconds = 0.0;
};

// Run the loop against `target`, growing `corpus` in place. Returns stats.
FuzzStats fuzz(TargetFn target, Corpus& corpus, const EngineOptions& opts);

}  // namespace nyx
